### ISSUE TITLE
首页统计图表数据查询全是0

### ISSUE THREAD

**Issue by 18696232390** [6324/xxl-job-admin-postgre#1]
<img width="1082" alt="54316FF5-ECAF-4079-806D-B09D7A763676" src="https://user-images.githubusercontent.com/44156273/123191993-a74e1680-d4d4-11eb-8557-de9d36eca9c1.png">

请问大佬如何解决呀

**Comment by 18696232390** [comment]
xxl_job_log_report 表一直是空的

**Comment by 18696232390** [comment]
@6324 大佬

**Comment by 1064112734** [comment]
有找到原因吗

**Comment by 1064112734** [comment]
我这边跟了下源码找到原因了，是因为postgre查询查询返回的字段默认是小写的XxlJobLogMapper.xml中的findLogReport这个方法里面SELECT
			COUNT(handle_code) as "triggerDayCount",
			SUM(CASE WHEN (trigger_code in (0, 200) and handle_code = 0) then 1 else 0 end) as "triggerDayCountRunning",
			SUM(CASE WHEN handle_code = 200 then 1 else 0 end) as "triggerDayCountSuc"
		FROM xxl_job_log
